### ISSUE TITLE
Scikit learn 0.20.3 fails

### ISSUE THREAD

**Issue by alex-ber** [alex-ber/alpine-anaconda3#1]
`
#!/usr/bin/python3

#taken from https://python.gotrained.com/tf-idf-twitter-sentiment-analysis/

import numpy as np 
import pandas as pd 
import re  
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
 
tweets = pd.read_csv("https://raw.githubusercontent.com/kolaveridi/kaggle-Twitter-US-Airline-Sentiment-/master/Tweets.csv")
 
print(tweets.head())
 
print(tweets.shape)

import matplotlib
matplotlib.use('PDF')

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='airline_sentiment', data=tweets)
plt.savefig("/opt/project/emrpythonconnect/figure_1")

sns.countplot(x='airline', data=tweets)
plt.savefig("/opt/project/emrpythonconnect/figure_2")

sns.countplot(x='airline', hue="airline_sentiment", data=tweets)
plt.savefig("/opt/project/emrpythonconnect/figure_3")

X = tweets.iloc[:, 10].values
y = tweets.iloc[:, 1].values

processed_tweets = []

for tweet in range(0, len(X)):
    # Remove all the special characters
    processed_tweet = re.sub(r'\W', ' ', str(X[tweet]))

    # remove all single characters
    processed_tweet = re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_tweet)

    # Remove single characters from the start
    processed_tweet = re.sub(r'\^[a-zA-Z]\s+', ' ', processed_tweet)

    # Substituting multiple spaces with single space
    processed_tweet= re.sub(r'\s+', ' ', processed_tweet, flags=re.I)

    # Removing prefixed 'b'
    processed_tweet = re.sub(r'^b\s+', '', processed_tweet)

    # Converting to Lowercase
    processed_tweet = processed_tweet.lower()

    processed_tweets.append(processed_tweet)

from sklearn.feature_extraction.text import TfidfVectorizer
tfidfconverter = TfidfVectorizer(max_features=2000, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = tfidfconverter.fit_transform(processed_tweets).toarray()
`

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6614dcba8ab6>", line 1, in <module>
    runfile('/opt/project/emrpythonconnect/check2.py', wdir='/opt/project/emrpythonconnect')
  File "/opt/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/opt/project/emrpythonconnect/check2.py", line 8, in <module>
    import nltk
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/__init__.py", line 143, in <module>
    from nltk.chunk import *
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/chunk/__init__.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.parse import ParserI
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/parse/__init__.py", line 100, in <module>
    from nltk.parse.transitionparser import TransitionParser
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/parse/transitionparser.py", line 22, in <module>
    from sklearn.datasets import load_svmlight_file
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py", line 14, in <module>
    from .utils.fixes import signature
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 14, in <module>
    from . import _joblib
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/_joblib.py", line 22, in <module>
    from ..externals import joblib
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from sklearn.externals.joblib.externals import cloudpickle  # noqa: F401
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 167, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 148, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

**Comment by alex-ber** [comment]
We have scikit-learn==0.20.3 that has joblib inside scikit-learn.
See https://github.com/scikit-learn/scikit-learn/issues/15800
https://stackoverflow.com/questions/58700384/how-to-fix-typeerror-an-integer-is-required-got-type-bytes-error-when-tryin
https://github.com/apache/spark/blob/v2.4.5/python/pyspark/cloudpickle.py#L78-L93 (patch)

Inherit from my docker file and add the following line:

pip install scikit-learn==0.22 joblib==0.14.1 

I will integrate this solution in next release.

**Comment by alex-ber** [comment]
Fixed in 0.0.4
