### ISSUE TITLE
nltk_data is absent

### ISSUE THREAD

**Issue by alex-ber** [alex-ber/alpine-anaconda3#2]
```python3
import pandas as pd 
from nltk.corpus import stopwords
print(stopwords.words('english'))
```

Failed with:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/data.py", line 701, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:
   import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html
  Attempted to load corpora/stopwords.zip/stopwords/
  Searched in:
    - '/root/nltk_data'
    - '/opt/anaconda3/nltk_data'
    - '/opt/anaconda3/share/nltk_data'
    - '/opt/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6614dcba8ab6>", line 1, in <module>
    runfile('/opt/project/emrpythonconnect/check2.py', wdir='/opt/project/emrpythonconnect')
  File "/opt/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/opt/project/emrpythonconnect/check2.py", line 11, in <module>
    print(stopwords.words('english'))
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/corpus/util.py", line 123, in __getattr__
    self.__load()
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/corpus/util.py", line 88, in __load
    raise e
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/corpus/util.py", line 83, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
  File "/opt/anaconda3/lib/python3.8/site-packages/nltk/data.py", line 701, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:
   import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html
  Attempted to load corpora/stopwords
  Searched in:
    - '/root/nltk_data'
    - '/opt/anaconda3/nltk_data'
    - '/opt/anaconda3/share/nltk_data'
    - '/opt/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

**Comment by alex-ber** [comment]
As work-around use 

```python3
import pandas as pd 
import re  
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
print(stopwords.words('english'))
```

Alternatively inherit from my dockerfile and add:

```dockerfile
#nltk-data
RUN set -ex && python -m nltk.downloader -d /usr/share/nltk_data all
```

In place of  /usr/share/nltk_data you can use any of the following path:

- '/root/nltk_data'
- '/opt/anaconda3/nltk_data'
- '/opt/anaconda3/share/nltk_data'
- '/opt/anaconda3/lib/nltk_data'
- '/usr/share/nltk_data'
- '/usr/local/share/nltk_data'
- '/usr/lib/nltk_data'
- '/usr/local/lib/nltk_data'


Note: You can set NLTK_DATA environment variable to point to your top level nltk_data folder. 
However, there many pitfalls in this process, so I'm recommended to use one of the standard locations.

**Comment by alex-ber** [comment]
nltk_data takes too much place, so I've decided not to include it to my dockerfile. 

If you need it, usually, you will need only some small subset of it, _download it youself or by creating custom image_ (you will do it only once, well, per dockerfile built) o_r directly in the Python code_ (it will be re-downloading every time you will restart your docker container; every code run, check will be done, whether filles was changed). See previous post for details.
